GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "anbiasenggagau",
    "password" : "asdasd"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "anbiasenggagau",
    "password" : "asdasd"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuYmlhc2VuZ2dhZ2F1IiwicGFzc3dvcmQiOiIkMmIkMTAkbHI3R2Y5RkcyYkovTS9uc05oSGFQT0VHZlZka3IzbzFxY2E0Nmp5QmlxQ25YdlZ5TGU2YnUiLCJpYXQiOjE2NDY2NDc0MDN9.diEiaMhQXUvql7GpD011Io7a1PbWHFCJ8U8cZE2mWj4