GET http://localhost:3001/subscribers

###

GET http://localhost:3001/subscribers/61ee4e07da0ffe01d0d4feff

###

POST http://localhost:3001/subscribers
Content-Type: application/json

{
    "name": "Senggagau",
    "subscribedToChannel" : "Web Dev Simplified"
}

###

DELETE http://localhost:3001/subscribers/621f1cebc8016ef82697c50f

###

PATCH http://localhost:3001/subscribers/61ee4de6da0ffe01d0d4fefd
Content-Type: application/json

{
    "name": "Seng",
    "subscribedToChannel" : "Anbia Bohlam"
}