GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/61ee4e07da0ffe01d0d4feff

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Senggagau",
    "subscribedToChannel" : "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/61ee4c81ab6aac5cce8aef2d

###

PATCH http://localhost:3000/subscribers/61ee4de6da0ffe01d0d4fefd
Content-Type: application/json

{
    "name": "Seng",
    "subscribedToChannel" : "Anbia Bohlam"
}